application: motorcico
version: 1
api_version: 1
runtime: python27
threadsafe: false
handlers:
  - url: /
    script: main.app
  - url: /index
    script: main.app
  - url: /result
    script: main.app
  - url: /index/cron
    script: cron_search.app
    login: admin
  - url: /robots.txt
    static_files: robots.txt
    upload: robots.txt
  - url: /index/task
    script: search_task.app
    login: admin
  - url: /index/index
    script: index_task.app
    login: admin

error_handlers:
  - file: templates/default_error.html